spring:
  application:
    name: earthquake-app

  kafka:
    bootstrap-servers: kafka:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  websocket:
    allowed-origins: "*"



  cassandra:
    contact-points: cassandra
    port: 9042
    keyspace-name: earthquake_keyspace
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS
server:
  port: 8086
  address: 0.0.0.0
